version: "3.9"

services:
  web:
    build: ./web
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
    env_file:
      - web/.env
    depends_on:
      - torchserve

  torchserve:
    build: ./torchserve
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
