version: "3.9"

services:
  web:
    build: ./web
    command: gunicorn -b :8000 car_detection.wsgi
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
    env_file:
      - web/.env
    depends_on:
      - torchserve

  torchserve:
    image: pytorch/torchserve:0.6.0-cpu
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
