version: "3.9"

services:
  web:
    build: ./web
    command: bash -c "python manage.py makemigrations detection && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -b :8000 car_detection.wsgi"
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
    env_file:
      - web/.env
    depends_on:
      - torchserve

  torchserve:
    build: ./torchserve
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
